
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Arayuz extends javax.swing.JFrame {
    Connection baglanti = null ;
    PreparedStatement pst = null ;
    ResultSet rs = null ;
/**
     * Creates new form Arayuz
     */
    public Arayuz() {
        initComponents();
        setIcon();
        goster_urun();
        
       // tablogoster();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBarkodNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUrunAd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnnrStok = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtAlisFiyat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSatisFiyat = new javax.swing.JTextField();
        ekleBtn = new javax.swing.JButton();
        guncelleBtn = new javax.swing.JButton();
        temizleBtn = new javax.swing.JButton();
        silBtn = new javax.swing.JButton();
        barkodSearchBtn = new javax.swing.JButton();
        urunAdSearchBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        webadress = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ürün Takip Yönetici Paneli");
        setLocationByPlatform(true);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod No", "Ürün Adı", "Ürün Stok", "Alış Fiyatı", "Satış Fiyatı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(200);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(2).setMinWidth(70);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(4).setMinWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Barkod No :");

        txtBarkodNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Ürün Adı :");

        txtUrunAd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Ürün Stok :");

        spnnrStok.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Alış Fiyatı :");

        txtAlisFiyat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Satış Fiyatı :");

        txtSatisFiyat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ekleBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ekleBtn.setForeground(new java.awt.Color(51, 51, 51));
        ekleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ekle2.png"))); // NOI18N
        ekleBtn.setText("Ekle");
        ekleBtn.setHideActionText(true);
        ekleBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ekleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ekleBtn.setIconTextGap(10);
        ekleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleBtnActionPerformed(evt);
            }
        });

        guncelleBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        guncelleBtn.setForeground(new java.awt.Color(51, 51, 51));
        guncelleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Başlıksız-7.png"))); // NOI18N
        guncelleBtn.setText("Güncelle");
        guncelleBtn.setHideActionText(true);
        guncelleBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guncelleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        guncelleBtn.setIconTextGap(10);
        guncelleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleBtnActionPerformed(evt);
            }
        });

        temizleBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        temizleBtn.setForeground(new java.awt.Color(51, 51, 51));
        temizleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Temizle3.png"))); // NOI18N
        temizleBtn.setText("Temizle");
        temizleBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        temizleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        temizleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleBtnActionPerformed(evt);
            }
        });

        silBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        silBtn.setForeground(new java.awt.Color(51, 51, 51));
        silBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Başlıksız-10.png"))); // NOI18N
        silBtn.setText("Sil");
        silBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        silBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        silBtn.setIconTextGap(10);
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        barkodSearchBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\urunTakipMy\\src\\img\\Başlıksız-6.png")); // NOI18N
        barkodSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barkodSearchBtnActionPerformed(evt);
            }
        });

        urunAdSearchBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\urunTakipMy\\src\\img\\Başlıksız-6.png")); // NOI18N
        urunAdSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunAdSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSatisFiyat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(txtAlisFiyat, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(txtBarkodNo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnnrStok, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUrunAd))))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barkodSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunAdSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temizleBtn)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(silBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guncelleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ekleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarkodNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUrunAd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(barkodSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urunAdSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnnrStok, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlisFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSatisFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addComponent(ekleBtn)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guncelleBtn)
                    .addComponent(temizleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silBtn)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Yönetici Arayüzü", jPanel1);

        jPanel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("! Sisteminizdeki herhangi bir ürünü silmek istiyorsanız barkod numarasını yazıp SİL butonuna basmalısınız.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("! Yönetici arayüzünde sağ tarafta bulunan tablo sisteminizde kayıtlı olan ürünleri ;  barkod numarası , ürün adı , stok , alış ve satış fiyatını");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("! TEMİZLE butonu ürün bilgisi girişi yaptığınız kutuları temizler.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("! Sistemde barkod numarasıyla arama yapmak için barkod numarasının bir kısmını veya tamamını girip yanındak ARAMA butonuna basmalısınız.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(182, 11, 90));
        jLabel11.setText("Karşılaşacağınız herhangi bir sorunda yazılımcıyla iletisime geçiniz.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("! Sisteminize ürün eklemek için soldaki kutuları ilişkisel olarak doldurarak EKLE butonuna basınız.Ürünün adı , alis fiyatı yada satış fiyatından herhangi");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("! Sisteminizdeki herhangi bir ürünün bilgilerini değiştirmek için önce barkod numarasıyla ürünü aratıp,tabloda seçtikten sonra soldan bilgileri değiştirerek");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("gruplandırarak listelemektedir.");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel24.setText("GÜNCELLE butonuna basmalısınız.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(182, 11, 90));
        jLabel25.setText("NOT : Ürünün barkod numarası güncellenemez.Ürünün barkod numarasını değiştirmek için ürünü silip tekrardan eklemelisiniz.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("birini doldurmamak istiyorsanız 0 yazmanız yeterlidir.");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(182, 11, 90));
        jLabel26.setText("NOT : Ürün eklerken barkod numarası boş bırakılamaz.Programdaki tüm işlemler barkod numarası üzerinden dönmektedir.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel23))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(7, 7, 7)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(9, 9, 9)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Yardım & Kullanım Klavuzu", jPanel2);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 99, 133));
        jLabel16.setText("İstek , görüş ve önerileriniz için :");

        webadress.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        webadress.setText("Web Site : www.berkantakyuz.com");
        webadress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webadressMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel18.setText("Cep Tel : 0538 366 9798");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel19.setText("E-mail : berkant_akyuz@hotmail.com");

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel21.setText("Adres : Kepeci Mah. 116 Cad. No : 17 ISPARTA / KUTLUBEY");

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel22.setText("Berkant Akyüz");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Programmer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(webadress)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22))
                            .addComponent(jLabel21)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(webadress)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("İletişim", jPanel4);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 137, 175));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tittle3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void temizleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleBtnActionPerformed

        temizle();
        sil_urun();
        goster_urun();
        
    }//GEN-LAST:event_temizleBtnActionPerformed

    private void ekleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleBtnActionPerformed
        ekle();
        sil_urun();
        goster_urun();
    }//GEN-LAST:event_ekleBtnActionPerformed

    private void guncelleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleBtnActionPerformed
        guncelle();
        sil_urun();
        goster_urun();
    }//GEN-LAST:event_guncelleBtnActionPerformed

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        sil();
        sil_urun();
        goster_urun();
        temizle();
    }//GEN-LAST:event_silBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          textFieldaGetir();
    }//GEN-LAST:event_jTable1MouseClicked

    private void barkodSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barkodSearchBtnActionPerformed
        sil_urun();
        urunarama_barkodNo();       
    }//GEN-LAST:event_barkodSearchBtnActionPerformed

    private void urunAdSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunAdSearchBtnActionPerformed
        sil_urun();
        urunarama_urunAd();
    }//GEN-LAST:event_urunAdSearchBtnActionPerformed

    private void webadressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webadressMouseClicked
        String url = "http://berkantakyuz.herokuapp.com/";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(Arayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_webadressMouseClicked
public void textFieldaGetir(){
    try{
            baglanti = veriTabaniBaglanti.Baglan();
            int row = jTable1.getSelectedRow();
            String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
            String sql = "select * from urun where barkodNo ="+tblclick+"";
            pst = baglanti.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String barkodNo = rs.getString("barkodNo");
                txtBarkodNo.setText(barkodNo);
                String urunAd = rs.getString("urunAd");
                txtUrunAd.setText(urunAd);
                //SPINNER STOK ---------
                int stok = rs.getInt("stok");
                spnnrStok.setValue(stok);
                //SPINNER STOK ---------
                String alisFiyat = String.valueOf(rs.getFloat("alisFiyat"));
                txtAlisFiyat.setText(alisFiyat);
                String satisFiyat = String.valueOf(rs.getFloat("satisFiyat"));
                txtSatisFiyat.setText(satisFiyat);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }

}
public void sil(){
    //Girilen barkod numaralı ürünü siler.
        baglanti = veriTabaniBaglanti.Baglan();
    try {
        String sql = "delete from urun where barkodNo=?";
        pst = baglanti.prepareStatement(sql);
        pst.setString(1,txtBarkodNo.getText());
        int donut = pst.executeUpdate();
        if(donut>0){
            JOptionPane.showMessageDialog(null,"Kayıt Başarı ile Silinmiştir.");
        }
        else
            JOptionPane.showMessageDialog(null,"Bu Barkod Numarasına Sahip Ürün Bulunamadı.\n");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Tsql komutları sırasında bir hata oluştu.\n."+e.getMessage());
   }
        
        



}
public void ekle(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            baglanti =DriverManager.getConnection("jdbc:mysql://localhost:3306/uruntakip","root","admin");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veri Tabanına Bağlantı Hatası!\n"+e.getMessage());
           }
        String sql = "insert into urun(barkodNo,urunAd,stok,alisFiyat,satisFiyat) values(?,?,?,?,?)";
        try {
            pst = baglanti.prepareStatement(sql);
            pst.setString(1,txtBarkodNo.getText());
            pst.setString(2,txtUrunAd.getText());
            pst.setInt(3, (int) spnnrStok.getValue());
            pst.setFloat(4,Float.valueOf(txtAlisFiyat.getText()));
            pst.setFloat(5,Float.valueOf(txtSatisFiyat.getText()));
            int donut = pst.executeUpdate();
        if(donut>0){
            JOptionPane.showMessageDialog(null,"Kayıt Başarı ile Eklenmiştir.");
        }
        else
            JOptionPane.showMessageDialog(null,"Kayıt Sırasında Bir Sorun Oluştu.\n Lütfen Üreticiyle İletişime Geçiniz. ");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Tsql Komutları Sırasında Bir Hata Oluştu.\n."+e.getMessage());
        }
           
}// ekle sonu
public void guncelle(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veri Tabanı Bağlantısı Driver Da Sorun Oluştu\n."+e.getMessage());
           }
        Connection baglanti = null ;
        try {
            baglanti =DriverManager.getConnection("jdbc:mysql://localhost:3306/uruntakip","root","admin");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veri Tabanına Bağlantı Hatası!\n"+e.getMessage());
        }
        String sql = "update urun set urunAd=? ,stok =? , alisFiyat=? , satisFiyat=?  where barkodNo=?";
          
            try {
                
                pst = baglanti.prepareStatement(sql);
                pst.setString(1,txtUrunAd.getText());
                pst.setInt(2,(int) spnnrStok.getValue());
                pst.setFloat(3,Float.valueOf(txtAlisFiyat.getText()));
                pst.setFloat(4,Float.valueOf(txtSatisFiyat.getText()));
                pst.setString(5,txtBarkodNo.getText());
                
                
                int donut = pst.executeUpdate();
        if(donut>0){
            JOptionPane.showMessageDialog(null,"Kayıt Başarı ile Güncellenmiştir.");
        }
        else
            JOptionPane.showMessageDialog(null,"Güncelleme Sırasında Bir Sorun Oluştu.\n Lütfen Üreticiyle İletişime Geçiniz. ");
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Sql Hatası.");
            }
 }//güncelle sonu 
public void temizle(){
           txtBarkodNo.setText(null);
           txtUrunAd.setText(null);
           spnnrStok.setValue(0);
           txtAlisFiyat.setText(null);
           txtSatisFiyat.setText(null);
}
public ArrayList<Urun> urunList(){
        ArrayList<Urun> urunsList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            baglanti =DriverManager.getConnection("jdbc:mysql://localhost:3306/uruntakip","root","admin");
            String sql = "select * from urun";
            Statement st =baglanti.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Urun urun ;
            while(rs.next()){
            urun = new Urun(rs.getString("barkodNo"),rs.getString("urunAd"),rs.getInt("stok"),rs.getFloat("alisFiyat"),rs.getFloat("satisFiyat"));
            urunsList.add(urun);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veri Tabanına Bağlantı Hatası!\n"+e.getMessage());
                              }
        return urunsList;
}
public void goster_urun(){
        //JTable doldurur.
        ArrayList<Urun> list = urunList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[5];
        for(int i =0 ; i<list.size();i++){
            row[0]=list.get(i).getbarkodNo();
            row[1]=list.get(i).geturunAd();
            row[2]=list.get(i).getstok();
            row[3]=list.get(i).getalisFiyat();
            row[4]=list.get(i).getsatisFiyat();
            model.addRow(row);  
        }

}
public void sil_urun(){
        //JTable temizler.
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        while(model.getRowCount()>0){
            for(int i = 0 ;i < model.getRowCount();i++){
                    model.removeRow(i);
            }
        }
}
public ArrayList<Urun> search_urunList_barkoNo(String ValToSearch)/* BARKOD NO İÇİN SEARCH */{
        ArrayList<Urun> urunsList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            baglanti =DriverManager.getConnection("jdbc:mysql://localhost:3306/uruntakip","root","admin");
            String sql = "SELECT * FROM `urun` WHERE CONCAT(`barkodNo`) LIKE '%"+ValToSearch+"%'";
            Statement st =baglanti.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Urun urun ;
            while(rs.next()){
            urun = new Urun(rs.getString("barkodNo"),rs.getString("urunAd"),rs.getInt("stok"),rs.getFloat("alisFiyat"),rs.getFloat("satisFiyat"));
            urunsList.add(urun);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veri Tabanına Bağlantı Hatası!\n"+e.getMessage());
                              }
        return urunsList;
}
public void urunarama_barkodNo(){
        String ValToSearch = txtBarkodNo.getText();
        ArrayList<Urun> list = search_urunList_barkoNo(ValToSearch);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[5];
        for(int i =0 ; i<list.size();i++){
            row[0]=list.get(i).getbarkodNo();
            row[1]=list.get(i).geturunAd();
            row[2]=list.get(i).getstok();
            row[3]=list.get(i).getalisFiyat();
            row[4]=list.get(i).getsatisFiyat();
            model.addRow(row);  
        }
}
public ArrayList<Urun> search_urunList_urunAd(String ValToSearch)/* URUN AD İÇİN SEARCH */{
        ArrayList<Urun> urunsList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            baglanti =DriverManager.getConnection("jdbc:mysql://localhost:3306/uruntakip","root","admin");
            String sql = "SELECT * FROM `urun` WHERE CONCAT(`urunAd`) LIKE '%"+ValToSearch+"%'";
            Statement st =baglanti.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Urun urun ;
            while(rs.next()){
            urun = new Urun(rs.getString("barkodNo"),rs.getString("urunAd"),rs.getInt("stok"),rs.getFloat("alisFiyat"),rs.getFloat("satisFiyat"));
            urunsList.add(urun);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veri Tabanına Bağlantı Hatası!\n"+e.getMessage());
                              }
        return urunsList;
}
public void urunarama_urunAd(){
        String ValToSearch = txtUrunAd.getText();
        ArrayList<Urun> list = search_urunList_urunAd(ValToSearch);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[5];
        for(int i =0 ; i<list.size();i++){
            row[0]=list.get(i).getbarkodNo();
            row[1]=list.get(i).geturunAd();
            row[2]=list.get(i).getstok();
            row[3]=list.get(i).getalisFiyat();
            row[4]=list.get(i).getsatisFiyat();
            model.addRow(row);  
        }
}




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barkodSearchBtn;
    private javax.swing.JButton ekleBtn;
    private javax.swing.JButton guncelleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton silBtn;
    private javax.swing.JSpinner spnnrStok;
    private javax.swing.JButton temizleBtn;
    private javax.swing.JTextField txtAlisFiyat;
    private javax.swing.JTextField txtBarkodNo;
    private javax.swing.JTextField txtSatisFiyat;
    private javax.swing.JTextField txtUrunAd;
    private javax.swing.JButton urunAdSearchBtn;
    private javax.swing.JLabel webadress;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png")));
    }
}
